spring:
  application:
    name: school-manager
  data:
    mongodb:
      host: ds117691.mlab.com
      port: 17691
      database: k12x-dev
      username: vkum985
      password: vkum985

server:
  port: 9011

logging:
  level:
    com:
      person:
        sam:
          school: INFO
    root: INFO
    org:
      springframework: INFO
