spring:
  application:
    name: organization-manager
  data:
    mongodb:
      host: ds117691.mlab.com
      port: 17691
      database: k12x-dev
      username: vkum985
      password: vkum985

server:
  port: 9012

logging:
  level:
    com:
      person:
        organization: INFO
    root: INFO
    org:
      springframework: INFO
